// backend/src/content/instructionPacks/en.ts

import type { PackEntry } from "./index";

export const EN_PACKS: Record<string, PackEntry> = {
  greetings_hello: {
    hint: ["Use a simple greeting like \"Hello\".", "A short, friendly greeting works well."],
    explanation: "\"Hello\" is a standard greeting.",
    feedbackWrong: "Try a simple greeting like \"Hello\".",
    feedbackAlmost: "Close - a simple \"Hello\" works best.",
    summary: "Use a short greeting to start.",
  },
  good_morning: {
    hint: ["Use this greeting before noon.", "Say \"Good morning\"."],
    explanation: "Say \"Good morning\" in the morning.",
    feedbackWrong: "Use \"Good morning\".",
    feedbackAlmost: "Almost - say \"Good morning\".",
    summary: "Morning greeting: \"Good morning\".",
  },
  good_afternoon: {
    hint: ["Use this greeting after noon.", "Say \"Good afternoon\"."],
    explanation: "Say \"Good afternoon\" in the afternoon.",
    feedbackWrong: "Use \"Good afternoon\".",
    feedbackAlmost: "Almost - say \"Good afternoon\".",
    summary: "Afternoon greeting: \"Good afternoon\".",
  },
  good_evening: {
    hint: ["Use this greeting in the evening.", "Say \"Good evening\"."],
    explanation: "Say \"Good evening\" in the evening.",
    feedbackWrong: "Use \"Good evening\".",
    feedbackAlmost: "Almost - say \"Good evening\".",
    summary: "Evening greeting: \"Good evening\".",
  },
  asking_name: {
    hint: ["Ask directly: \"What is your name?\"", "A polite question works best."],
    explanation: "\"What is your name?\" is a common polite question.",
    feedbackWrong: "Ask: \"What is your name?\"",
    feedbackAlmost: "Close - try \"What is your name?\"",
    summary: "Ask with \"What is your name?\"",
  },
  introduce_self: {
    hint: ["Start with \"My name is ...\".", "Keep it short and clear."],
    explanation: "Use \"My name is ...\" to introduce yourself.",
    feedbackWrong: "Start with \"My name is ...\".",
    feedbackAlmost: "Almost - try \"My name is ...\".",
    summary: "Use \"My name is ...\".",
  },
  asking_how_are_you: {
    hint: ["Ask: \"How are you?\"", "It is a friendly check-in."],
    explanation: "\"How are you?\" is a common friendly question.",
    feedbackWrong: "Ask: \"How are you?\"",
    feedbackAlmost: "Close - \"How are you?\"",
    summary: "Ask \"How are you?\"",
  },
  how_are_you_reply: {
    hint: ["Reply with \"I'm fine, thank you.\"", "Start with \"I'm ...\""],
    explanation: "A polite reply is \"I'm fine, thank you.\"",
    feedbackWrong: "Reply: \"I'm fine, thank you.\"",
    feedbackAlmost: "Almost - \"I'm fine, thank you.\"",
    summary: "Reply politely: \"I'm fine, thank you.\"",
  },
  nice_to_meet_you: {
    hint: ["Say it after introductions.", "Use \"Nice to meet you.\""],
    explanation: "It is a polite phrase after meeting someone.",
    feedbackWrong: "Say \"Nice to meet you.\"",
    feedbackAlmost: "Close - \"Nice to meet you.\"",
    summary: "Use \"Nice to meet you.\"",
  },
  goodbye: {
    hint: ["Use \"Goodbye\" or \"Bye.\"", "A simple farewell works."],
    explanation: "\"Goodbye\" is standard; \"Bye\" is informal.",
    feedbackWrong: "Say \"Goodbye\" or \"Bye.\"",
    feedbackAlmost: "Almost - \"Goodbye\" works.",
    summary: "Use a simple farewell.",
  },
  number_1: {
    hint: ["It is the word for 1.", "It starts with \"o\"."],
    explanation: "The word for 1 is \"one\".",
    feedbackWrong: "Use \"one\".",
    feedbackAlmost: "Close - \"one\".",
    summary: "1 -> \"one\".",
  },
  number_2: {
    hint: ["It is the word for 2.", "It starts with \"t\"."],
    explanation: "The word for 2 is \"two\".",
    feedbackWrong: "Use \"two\".",
    feedbackAlmost: "Close - \"two\".",
    summary: "2 -> \"two\".",
  },
  number_3: {
    hint: ["It is the word for 3.", "It starts with \"th\"."],
    explanation: "The word for 3 is \"three\".",
    feedbackWrong: "Use \"three\".",
    feedbackAlmost: "Close - \"three\".",
    summary: "3 -> \"three\".",
  },
  number_4: {
    hint: ["It is the word for 4.", "It starts with \"f\"."],
    explanation: "The word for 4 is \"four\".",
    feedbackWrong: "Use \"four\".",
    feedbackAlmost: "Close - \"four\".",
    summary: "4 -> \"four\".",
  },
  number_5: {
    hint: ["It is the word for 5.", "It starts with \"f\"."],
    explanation: "The word for 5 is \"five\".",
    feedbackWrong: "Use \"five\".",
    feedbackAlmost: "Close - \"five\".",
    summary: "5 -> \"five\".",
  },
  color_blue: {
    hint: ["Think of a clear sky.", "It is a basic color word."],
    explanation: "A clear sky is usually blue.",
    feedbackWrong: "Try \"blue\".",
    feedbackAlmost: "Almost - \"blue\".",
    summary: "Sky color: blue.",
  },
  color_red: {
    hint: ["A common apple color is red.", "It is a basic color word."],
    explanation: "Apples are often red.",
    feedbackWrong: "Try \"red\".",
    feedbackAlmost: "Almost - \"red\".",
    summary: "Apple color: red.",
  },
  color_green: {
    hint: ["Think of grass.", "It is a basic color word."],
    explanation: "Grass is typically green.",
    feedbackWrong: "Try \"green\".",
    feedbackAlmost: "Almost - \"green\".",
    summary: "Grass color: green.",
  },
  color_black: {
    hint: ["It is the opposite of white.", "Think of the night."],
    explanation: "A simple color word for night is \"black\".",
    feedbackWrong: "Try \"black\".",
    feedbackAlmost: "Almost - \"black\".",
    summary: "Night color: black.",
  },
  color_white: {
    hint: ["Think of snow.", "It is a basic color word."],
    explanation: "Snow is typically white.",
    feedbackWrong: "Try \"white\".",
    feedbackAlmost: "Almost - \"white\".",
    summary: "Snow color: white.",
  },
  "a1_present_like_i": {
    hint: ["Start with: I like …"],
    explanation: "Use “I like …” to say what you enjoy.",
    feedbackAlmost: "Almost. Use: I like + thing.",
    feedbackWrong: "Try again. Start with: I like …",
    summary: "Pattern: I like + noun. Example: I like coffee.",
  },
  "a1_present_like_you": {
    hint: ["Start with: You like …"],
    explanation: "Use “You like …” when speaking to someone.",
    feedbackAlmost: "Close. Use: You like + thing.",
    feedbackWrong: "Try: You like …",
    summary: "Pattern: You like + noun. Example: You like tea.",
  },
  "a1_present_have_i": {
    hint: ["Start with: I have …"],
    explanation: "Use “I have …” to say what you own or have with you.",
    feedbackAlmost: "Almost. Use: I have + a/an + noun.",
    feedbackWrong: "Try again: I have …",
    summary: "Pattern: I have + noun. Example: I have a phone.",
  },
  "a1_present_have_we": {
    hint: ["Start with: We have …"],
    explanation: "Use “We have …” for you + other people.",
    feedbackAlmost: "Close. Use: We have …",
    feedbackWrong: "Try: We have …",
    summary: "Pattern: We have + noun. Example: We have a plan.",
  },
  "a1_present_want_i": {
    hint: ["Start with: I want …"],
    explanation: "Use “I want …” to say what you need or would like.",
    feedbackAlmost: "Almost. Use: I want + thing.",
    feedbackWrong: "Try again: I want …",
    summary: "Pattern: I want + noun. Example: I want water.",
  },
  "a1_present_want_they": {
    hint: ["Start with: They want …"],
    explanation: "Use “They want …” for people (plural).",
    feedbackAlmost: "Close. Use: They want …",
    feedbackWrong: "Try: They want …",
    summary: "Pattern: They want + noun. Example: They want help.",
  },
  "a1_present_and_objects": {
    hint: ["Use “and” to join two things."],
    explanation: "Use “and” to connect two items: apples and bananas.",
    feedbackAlmost: "Close. Join the two items with “and”.",
    feedbackWrong: "Try again: … and …",
    summary: "Join: X and Y. Example: apples and bananas.",
  },
  "a1_present_have_number": {
    hint: ["Put the number before the noun."],
    explanation: "Numbers go before nouns: two chairs, three books.",
    feedbackAlmost: "Almost. Put the number first: two chairs.",
    feedbackWrong: "Try: We have two …",
    summary: "Pattern: number + noun. Example: two chairs.",
  },
  "a1_present_want_to": {
    hint: ["Use: want to + verb."],
    explanation: "Use “want to” before a verb: want to go / want to eat.",
    feedbackAlmost: "Close. Use: want to + verb.",
    feedbackWrong: "Try again: I want to …",
    summary: "Pattern: want to + verb. Example: I want to go.",
  },
  "a1_present_here_it": {
    hint: ["Put “here” at the end."],
    explanation: "“Here” shows location: I have it here.",
    feedbackAlmost: "Almost. Put “here” at the end.",
    feedbackWrong: "Try: I have it here.",
    summary: "Location word: here. Example: I have it here.",
  },
  "a1_present3_likes": {
    hint: ["With he/she/it: add -s (like → likes)."],
    explanation: "With he/she/it in the present simple, add -s: he likes, she likes.",
    feedbackAlmost: "Close. Remember the -s: likes.",
    feedbackWrong: "Try again: He likes … / She likes …",
    summary: "He/She/It + verb+s. Example: She likes tea.",
  },
  "a1_present3_has": {
    hint: ["With he/she/it: have → has."],
    explanation: "Use “has” with he/she/it: he has, she has, it has.",
    feedbackAlmost: "Almost. Use: has (not have).",
    feedbackWrong: "Try: He has … / She has …",
    summary: "He/She/It has. Example: He has a car.",
  },
  "a1_present3_wants": {
    hint: ["With he/she/it: want → wants."],
    explanation: "With he/she/it, add -s: it wants, he wants, she wants.",
    feedbackAlmost: "Close. Add -s: wants.",
    feedbackWrong: "Try: It wants …",
    summary: "He/She/It + verb+s. Example: It wants water.",
  },
  "a1_present3_does_question": {
    hint: ["Question: Does + subject + base verb …?"],
    explanation: "After “Does”, use the base verb: Does she like…? Does he have…?",
    feedbackAlmost: "Close. After “Does”, use base form (like/have).",
    feedbackWrong: "Try: Does + subject + like/have …?",
    summary: "Does + subject + base verb. Example: Does he like tea?",
  },
  "a1_present3_does_not": {
    hint: ["Negative: doesn’t + base verb (no -s)."],
    explanation: "With “doesn’t”, use base verb: doesn’t like (not likes).",
    feedbackAlmost: "Almost. Use base verb after doesn’t: like/want/have.",
    feedbackWrong: "Try: He doesn’t like … / She doesn’t want …",
    summary: "doesn’t + base verb. Example: He doesn’t like milk.",
  },
  "a1_present3_short_answer": {
    hint: ["Short answers: Yes, he does. / No, he doesn’t."],
    explanation: "For does-questions, short answers use does/doesn’t.",
    feedbackAlmost: "Close. Use: Yes, he does. / No, he doesn’t.",
    feedbackWrong: "Try: Yes, he does.",
    summary: "Short answer uses does. Example: Yes, he does.",
  },
  "a1_q_do_yesno": {
    hint: ["Start with: Do you …?"],
    explanation: "Use “Do” for I/you/we/they + base verb: Do you like…?",
    feedbackAlmost: "Close. Start with “Do you …?” and use the base verb.",
    feedbackWrong: "Try again: Do you + verb …?",
    summary: "Do + subject + base verb. Example: Do you like coffee?",
  },
  "a1_q_where_do": {
    hint: ["Use: Where do you …?"],
    explanation: "W-question pattern: Where + do + subject + base verb.",
    feedbackAlmost: "Close. Use: Where do you + verb …?",
    feedbackWrong: "Try: Where do you live?",
    summary: "Where + do + subject + base verb. Example: Where do you live?",
  },
  "a1_q_what_do": {
    hint: ["Use: What do you …?"],
    explanation: "Use “What do you …?” to ask about things: What do you want?",
    feedbackAlmost: "Close. Use: What do you + verb …?",
    feedbackWrong: "Try: What do you want?",
    summary: "What + do + subject + base verb. Example: What do you want?",
  },
  "a1_q_do_yesno_we": {
    hint: ["Start with: Do we …?"],
    explanation: "Use “Do” with we/they: Do we have time?",
    feedbackAlmost: "Close. Use: Do we + base verb …?",
    feedbackWrong: "Try: Do we have time?",
    summary: "Do + we/they + base verb. Example: Do we have time?",
  },
  "a1_q_does_yesno": {
    hint: ["Start with: Does he/she/it …?"],
    explanation: "Use “Does” with he/she/it, then base verb (no -s): Does he like…?",
    feedbackAlmost: "Close. After “Does”, use base verb: like/have (no -s).",
    feedbackWrong: "Try: Does he like tea?",
    summary: "Does + he/she/it + base verb. Example: Does she like coffee?",
  },
  "a1_q_where_does": {
    hint: ["Use: Where does he/she …?"],
    explanation: "After “does”, use base verb: Where does she live? (not lives).",
    feedbackAlmost: "Close. Use base verb after does: live/work/have.",
    feedbackWrong: "Try: Where does she live?",
    summary: "Where + does + subject + base verb. Example: Where does she live?",
  },
  "a1_q_short_answer_do_yes": {
    hint: ["Short answer: Yes, I do."],
    explanation: "For do-questions, short answers use do/don’t: Yes, I do.",
    feedbackAlmost: "Close. Use: Yes, I do.",
    feedbackWrong: "Try: Yes, I do.",
    summary: "Yes/No + subject + do/don’t. Example: Yes, I do.",
  },
  "a1_q_short_answer_do_no": {
    hint: ["Short answer: No, I don't."],
    explanation: "“Don’t” means “do not”. Use it in short answers: No, I don’t.",
    feedbackAlmost: "Close. Use: No, I don't.",
    feedbackWrong: "Try: No, I don't.",
    summary: "No + subject + don't. Example: No, I don't.",
  },
  "a1_q_short_answer_does_yes": {
    hint: ["Short answer: Yes, he does."],
    explanation: "For does-questions, short answers use does/doesn’t: Yes, he does.",
    feedbackAlmost: "Close. Use: Yes, he does.",
    feedbackWrong: "Try: Yes, he does.",
    summary: "Yes + subject + does. Example: Yes, he does.",
  },
  "a1_q_short_answer_does_no": {
    hint: ["Short answer: No, she doesn't."],
    explanation: "“Doesn’t” means “does not”. Use it in short answers: No, she doesn’t.",
    feedbackAlmost: "Close. Use: No, she doesn't.",
    feedbackWrong: "Try: No, she doesn't.",
    summary: "No + subject + doesn't. Example: No, she doesn't.",
  },
  "a1_thereis_singular": {
    hint: ["Use: There is + a/an + noun."],
    explanation: "Use “There is” for one thing: There is a book.",
    feedbackAlmost: "Close. Use “There is” for one thing.",
    feedbackWrong: "Try: There is a …",
    summary: "There is = one thing. Example: There is a chair.",
  },
  "a1_thereare_plural": {
    hint: ["Use: There are + number + plural noun."],
    explanation: "Use “There are” for more than one: There are two chairs.",
    feedbackAlmost: "Close. Use “There are” + plural noun.",
    feedbackWrong: "Try: There are two …",
    summary: "There are = 2+ things. Example: There are three books.",
  },
  "a1_article_a": {
    hint: ["Use “a” before a consonant sound."],
    explanation: "Use “a” with singular nouns: a phone, a book.",
    feedbackAlmost: "Close. Use “a” here.",
    feedbackWrong: "Try: a + noun",
    summary: "a + singular noun. Example: a phone.",
  },
  "a1_article_an": {
    hint: ["Use “an” before a vowel sound."],
    explanation: "Use “an” with vowel sounds: an apple, an umbrella.",
    feedbackAlmost: "Close. Use “an” here.",
    feedbackWrong: "Try: an + noun",
    summary: "an + vowel sound. Example: an apple.",
  },
  "a1_article_the_known": {
    hint: ["Use “the” for a specific thing."],
    explanation: "Use “the” when it’s clear which one: the book, the door.",
    feedbackAlmost: "Close. Use “the” for a specific item.",
    feedbackWrong: "Try: the + noun",
    summary: "the = specific. Example: The book is here.",
  },
  "a1_thereis_location": {
    hint: ["Put “here” at the end."],
    explanation: "Add location words at the end: There is a table here.",
    feedbackAlmost: "Close. Put “here” at the end.",
    feedbackWrong: "Try: … here.",
    summary: "Location word at end. Example: There is a chair here.",
  },
  "a1_thereare_in_room": {
    hint: ["Use: There are + number + plural + in the room."],
    explanation: "Use “There are” + number + plural noun + place.",
    feedbackAlmost: "Close. Use plural noun after the number.",
    feedbackWrong: "Try: There are three … in the room.",
    summary: "There are + number + plural + place. Example: There are two chairs in the room.",
  },
  "a1_article_choice_a_an": {
    hint: ["Use “an” before a vowel sound."],
    explanation: "Choose a/an by sound: an umbrella (vowel sound).",
    feedbackAlmost: "Close. Umbrella uses “an”.",
    feedbackWrong: "Try: an umbrella",
    summary: "an + vowel sound. Example: an umbrella.",
  },
  "a1_article_choice_the": {
    hint: ["Use “the” when it’s clear which one."],
    explanation: "Use “the” for something specific: the door, the window.",
    feedbackAlmost: "Close. Use “the” here.",
    feedbackWrong: "Try: The door …",
    summary: "the = specific. Example: The door is open.",
  },
  "a1_thereis_question_is_there": {
    hint: ["Start with: Is there …?"],
    explanation: "Use “Is there …?” to ask about one thing: Is there a chair?",
    feedbackAlmost: "Close. Start with “Is there …?”",
    feedbackWrong: "Try: Is there a …?",
    summary: "Is there = question (one thing). Example: Is there a book?",
  },

  "a1_poss_my": {
    hint: ["Use: my + noun."],
    explanation: "“My” shows something belongs to me.",
    feedbackAlmost: "Close. Put “my” before the noun.",
    feedbackWrong: "Try: my + noun.",
    summary: "my = belongs to me. Example: my book.",
  },
  "a1_poss_your": {
    hint: ["Use: your + noun."],
    explanation: "“Your” shows something belongs to you.",
    feedbackAlmost: "Close. Put “your” before the noun.",
    feedbackWrong: "Try: your + noun.",
    summary: "your = belongs to you. Example: your phone.",
  },
  "a1_poss_his": {
    hint: ["Use: his + noun."],
    explanation: "“His” is for a man or boy.",
    feedbackAlmost: "Close. Put “his” before the noun.",
    feedbackWrong: "Try: his + noun.",
    summary: "his = male owner. Example: his car.",
  },
  "a1_poss_her": {
    hint: ["Use: her + noun."],
    explanation: "“Her” is for a woman or girl.",
    feedbackAlmost: "Close. Put “her” before the noun.",
    feedbackWrong: "Try: her + noun.",
    summary: "her = female owner. Example: her bag.",
  },
  "a1_family_mother": {
    hint: ["Use: This is my mother."],
    explanation: "“Mother” is a parent (female).",
    feedbackAlmost: "Close. Use: This is my mother.",
    feedbackWrong: "Try: This is my mother.",
    summary: "mother = female parent.",
  },
  "a1_family_father": {
    hint: ["Use: This is my father."],
    explanation: "“Father” is a parent (male).",
    feedbackAlmost: "Close. Use: This is my father.",
    feedbackWrong: "Try: This is my father.",
    summary: "father = male parent.",
  },
  "a1_family_sister": {
    hint: ["Use: I have a sister."],
    explanation: "Use “a” before sister.",
    feedbackAlmost: "Close. Use: I have a sister.",
    feedbackWrong: "Try: I have a sister.",
    summary: "sister = female sibling.",
  },
  "a1_family_brother": {
    hint: ["Use: I have a brother."],
    explanation: "Use “a” before brother.",
    feedbackAlmost: "Close. Use: I have a brother.",
    feedbackWrong: "Try: I have a brother.",
    summary: "brother = male sibling.",
  },
  "a1_desc_simple_age": {
    hint: ["Use: is + number."],
    explanation: "Use “is” + number for age.",
    feedbackAlmost: "Close. Use: is + number.",
    feedbackWrong: "Try: My mother is 40.",
    summary: "Age: is + number.",
  },
  "a1_q_whose": {
    hint: ["Start with: Whose …?"],
    explanation: "“Whose” asks about ownership.",
    feedbackAlmost: "Close. Use: Whose + noun …?",
    feedbackWrong: "Try: Whose book is this?",
    summary: "Whose = ownership question.",
  },
  "a1_time_what_time_is_it": {
    hint: ["Start with: What time is it?"],
    explanation: "Use this to ask the current time.",
    feedbackAlmost: "Close. Use: What time is it?",
    feedbackWrong: "Try: What time is it?",
    summary: "Ask the time: What time is it?",
  },
  "a1_time_oclock": {
    hint: ["Use: It is … o'clock."],
    explanation: "Use “o'clock” for exact hours.",
    feedbackAlmost: "Close. Use: It's … o'clock.",
    feedbackWrong: "Try: It's three o'clock.",
    summary: "o'clock = exact hour.",
  },
  "a1_routine_wake_up": {
    hint: ["Use: at + time."],
    explanation: "Use “at” with times: at 7.",
    feedbackAlmost: "Close. Use: I wake up at 7.",
    feedbackWrong: "Try: I wake up at 7.",
    summary: "at + time.",
  },
  "a1_routine_go_to_work": {
    hint: ["Use: go to work."],
    explanation: "Use “go to work” for your routine.",
    feedbackAlmost: "Close. Use: I go to work at 9.",
    feedbackWrong: "Try: I go to work at 9.",
    summary: "go to work.",
  },
  "a1_routine_go_home": {
    hint: ["Use: go home."],
    explanation: "Use “go home” to say you return home.",
    feedbackAlmost: "Close. Use: I go home at 5.",
    feedbackWrong: "Try: I go home at 5.",
    summary: "go home.",
  },
  "a1_days_on_monday": {
    hint: ["Use: on + day."],
    explanation: "Use “on” with days: on Monday.",
    feedbackAlmost: "Close. Put “on Monday” at the end.",
    feedbackWrong: "Try: I work on Monday.",
    summary: "on + day.",
  },
  "a1_frequency_always": {
    hint: ["Put “always” before the verb."],
    explanation: "Frequency words often go before the main verb.",
    feedbackAlmost: "Close. Put “always” before the verb.",
    feedbackWrong: "Try: I always drink water.",
    summary: "always = 100%.",
  },
  "a1_frequency_sometimes": {
    hint: ["Put “sometimes” before the verb."],
    explanation: "“Sometimes” means not every day.",
    feedbackAlmost: "Close. Put “sometimes” before the verb.",
    feedbackWrong: "Try: I sometimes eat pizza.",
    summary: "sometimes = not always.",
  },
  "a1_frequency_never": {
    hint: ["Put “never” before the verb."],
    explanation: "“Never” means 0% of the time.",
    feedbackAlmost: "Close. Put “never” before the verb.",
    feedbackWrong: "Try: I never smoke.",
    summary: "never = 0%.",
  },
  "a1_q_when": {
    hint: ["Start with: When do you …?"],
    explanation: "Use “When do you …?” to ask about time.",
    feedbackAlmost: "Close. Use: When do you + verb …?",
    feedbackWrong: "Try: When do you wake up?",
    summary: "When + do + subject + verb.",
  },
  "a1_can_ability_i": {
    hint: ["Use: I can + verb."],
    explanation: "“Can” shows ability.",
    feedbackAlmost: "Close. Use: I can + verb.",
    feedbackWrong: "Try: I can swim.",
    summary: "can = ability.",
  },
  "a1_can_ability_you": {
    hint: ["Start with: Can you …?"],
    explanation: "Use “Can you …?” to ask about ability.",
    feedbackAlmost: "Close. Use: Can you + verb …?",
    feedbackWrong: "Try: Can you swim?",
    summary: "Can you + verb?",
  },
  "a1_can_short_yes": {
    hint: ["Short answer: Yes, I can."],
    explanation: "Short answers use can/can't.",
    feedbackAlmost: "Close. Use: Yes, I can.",
    feedbackWrong: "Try: Yes, I can.",
    summary: "Yes + subject + can.",
  },
  "a1_can_short_no": {
    hint: ["Short answer: No, I can't."],
    explanation: "“Can't” means “cannot”.",
    feedbackAlmost: "Close. Use: No, I can't.",
    feedbackWrong: "Try: No, I can't.",
    summary: "No + subject + can't.",
  },
  "a1_can_negative": {
    hint: ["Use: can't + verb."],
    explanation: "Use “can't” for not able.",
    feedbackAlmost: "Close. Use: can't + verb.",
    feedbackWrong: "Try: I can't cook.",
    summary: "can't = not able.",
  },
  "a1_request_can_you": {
    hint: ["Start with: Can you …?"],
    explanation: "“Can you …?” can be a request.",
    feedbackAlmost: "Close. Use: Can you + verb …?",
    feedbackWrong: "Try: Can you help me?",
    summary: "Can you …? (request).",
  },
  "a1_request_please": {
    hint: ["Start with: Please …"],
    explanation: "“Please” makes it polite.",
    feedbackAlmost: "Close. Put “Please” first.",
    feedbackWrong: "Try: Please help me.",
    summary: "Please = polite.",
  },
  "a1_request_can_i": {
    hint: ["Start with: Can I …?"],
    explanation: "Use “Can I …?” to ask permission.",
    feedbackAlmost: "Close. Use: Can I + verb …?",
    feedbackWrong: "Try: Can I use your phone?",
    summary: "Can I …? (permission).",
  },
  "a1_can_ability_he": {
    hint: ["Use: He can + verb."],
    explanation: "“Can” stays the same for he/she/it.",
    feedbackAlmost: "Close. Use: He can + verb.",
    feedbackWrong: "Try: He can drive.",
    summary: "can stays the same.",
  },
  "a1_can_question_can_she": {
    hint: ["Start with: Can she …?"],
    explanation: "Use “Can” + subject + verb.",
    feedbackAlmost: "Close. Use: Can she + verb …?",
    feedbackWrong: "Try: Can she cook?",
    summary: "Can + subject + verb?",
  },
  "a1_imp_sit": {
    hint: ["Use the verb alone."],
    explanation: "Imperatives use the base verb.",
    feedbackAlmost: "Close. Just say: Sit down.",
    feedbackWrong: "Try: Sit down.",
    summary: "Imperative = base verb.",
  },
  "a1_imp_stand": {
    hint: ["Use the verb alone."],
    explanation: "This is a simple command.",
    feedbackAlmost: "Close. Just say: Stand up.",
    feedbackWrong: "Try: Stand up.",
    summary: "Simple command.",
  },
  "a1_imp_open": {
    hint: ["Start with: Open …"],
    explanation: "Use “the” for a specific door.",
    feedbackAlmost: "Close. Use: Open the door.",
    feedbackWrong: "Try: Open the door.",
    summary: "Open + the + noun.",
  },
  "a1_imp_close": {
    hint: ["Start with: Close …"],
    explanation: "Imperatives can be polite with “please”.",
    feedbackAlmost: "Close. Use: Close the window.",
    feedbackWrong: "Try: Close the window.",
    summary: "Close + the + noun.",
  },
  "a1_dir_go_straight": {
    hint: ["Use: Go + direction."],
    explanation: "“Go straight” means continue forward.",
    feedbackAlmost: "Close. Say: Go straight.",
    feedbackWrong: "Try: Go straight.",
    summary: "Go + direction.",
  },
  "a1_dir_turn_left": {
    hint: ["Use: Turn + left."],
    explanation: "This is a direction.",
    feedbackAlmost: "Close. Say: Turn left.",
    feedbackWrong: "Try: Turn left.",
    summary: "Turn + left.",
  },
  "a1_dir_turn_right": {
    hint: ["Use: Turn + right."],
    explanation: "This is a direction.",
    feedbackAlmost: "Close. Say: Turn right.",
    feedbackWrong: "Try: Turn right.",
    summary: "Turn + right.",
  },
  "a1_imp_please": {
    hint: ["Start with: Please …"],
    explanation: "“Please” makes a command polite.",
    feedbackAlmost: "Close. Put “Please” first.",
    feedbackWrong: "Try: Please wait.",
    summary: "Please + verb.",
  },
  "a1_q_where_is": {
    hint: ["Start with: Where is …?"],
    explanation: "Use “Where is …?” to ask for location.",
    feedbackAlmost: "Close. Use: Where is the …?",
    feedbackWrong: "Try: Where is the station?",
    summary: "Where is + place?",
  },
  "a1_imp_stop": {
    hint: ["Use: Stop + here."],
    explanation: "“Stop here” means stop at this place.",
    feedbackAlmost: "Close. Say: Stop here.",
    feedbackWrong: "Try: Stop here.",
    summary: "Stop + here.",
  },
  "a1_food_id_like": {
    hint: ["Use: I'd like + noun."],
    explanation: "“I'd like” is polite for ordering.",
    feedbackAlmost: "Close. Use: I'd like + noun.",
    feedbackWrong: "Try: I'd like water, please.",
    summary: "I'd like = polite order.",
  },
  "a1_food_please": {
    hint: ["One polite word."],
    explanation: "“Please” makes requests polite.",
    feedbackAlmost: "Close. Say: Please.",
    feedbackWrong: "Try: Please.",
    summary: "Please = polite.",
  },
  "a1_food_thank_you": {
    hint: ["A polite reply."],
    explanation: "Use “Thank you” or “Thanks”.",
    feedbackAlmost: "Close. Say: Thank you.",
    feedbackWrong: "Try: Thank you.",
    summary: "Thank you = polite.",
  },
  "a1_food_how_much": {
    hint: ["Start with: How much …?"],
    explanation: "Use this to ask about price.",
    feedbackAlmost: "Close. Use: How much is this?",
    feedbackWrong: "Try: How much is this?",
    summary: "How much = price question.",
  },
  "a1_food_how_much_item": {
    hint: ["Use: How much is the …?"],
    explanation: "Use “the” for a specific item.",
    feedbackAlmost: "Close. Use: How much is the coffee?",
    feedbackWrong: "Try: How much is the coffee?",
    summary: "How much is the + item.",
  },
  "a1_food_i_want": {
    hint: ["Use: I want + noun."],
    explanation: "“I want” is direct. “I'd like” is more polite.",
    feedbackAlmost: "Close. Use: I want + noun.",
    feedbackWrong: "Try: I want a sandwich.",
    summary: "I want = direct.",
  },
  "a1_food_do_you_have": {
    hint: ["Start with: Do you have …?"],
    explanation: "Use “Do you have …?” to ask availability.",
    feedbackAlmost: "Close. Use: Do you have + noun?",
    feedbackWrong: "Try: Do you have water?",
    summary: "Do you have …?",
  },
  "a1_food_yes_we_do": {
    hint: ["Short answer: Yes, we do."],
    explanation: "Short answers use do/don't.",
    feedbackAlmost: "Close. Use: Yes, we do.",
    feedbackWrong: "Try: Yes, we do.",
    summary: "Yes + we do.",
  },
  "a1_food_no_we_dont": {
    hint: ["Short answer: No, we don't."],
    explanation: "“Don't” means “do not”.",
    feedbackAlmost: "Close. Use: No, we don't.",
    feedbackWrong: "Try: No, we don't.",
    summary: "No + we don't.",
  },
  "a1_review_greeting": {
    hint: ["Morning greeting."],
    explanation: "Use this greeting before noon.",
    feedbackAlmost: "Close. Say: Good morning.",
    feedbackWrong: "Try: Good morning.",
    summary: "Morning greeting.",
  },
  "a1_review_name_question": {
    hint: ["Start with: What is …?"],
    explanation: "“What's” means “What is”.",
    feedbackAlmost: "Close. Use: What's your name?",
    feedbackWrong: "Try: What's your name?",
    summary: "Ask a name.",
  },
  "a1_review_introduce": {
    hint: ["Use: My name is …"],
    explanation: "This is a simple introduction.",
    feedbackAlmost: "Close. Use: My name is …",
    feedbackWrong: "Try: My name is Alex.",
    summary: "Introduce: My name is …",
  },
  "a1_review_do_question": {
    hint: ["Start with: Do you …?"],
    explanation: "Use “Do” + base verb: like.",
    feedbackAlmost: "Close. Use: Do you like …?",
    feedbackWrong: "Try: Do you like tea?",
    summary: "Do + base verb.",
  },
  "a1_review_short_yes": {
    hint: ["Short answer."],
    explanation: "Short answers use do/don't.",
    feedbackAlmost: "Close. Use: Yes, I do.",
    feedbackWrong: "Try: Yes, I do.",
    summary: "Yes, I do.",
  },
  "a1_review_there_is": {
    hint: ["Use: There is + a + noun."],
    explanation: "“There is” is for one thing.",
    feedbackAlmost: "Close. Use: There is a chair.",
    feedbackWrong: "Try: There is a chair.",
    summary: "There is = one thing.",
  },
  "a1_review_possessive": {
    hint: ["Use: my + noun."],
    explanation: "“My” shows ownership.",
    feedbackAlmost: "Close. Use: This is my phone.",
    feedbackWrong: "Try: This is my phone.",
    summary: "my = ownership.",
  },
  "a1_review_can": {
    hint: ["Start with: Can you …?"],
    explanation: "“Can you …?” can be a request.",
    feedbackAlmost: "Close. Use: Can you help me?",
    feedbackWrong: "Try: Can you help me?",
    summary: "Can you …? (request).",
  },
  "a1_review_direction": {
    hint: ["Direction phrase."],
    explanation: "This is a simple direction.",
    feedbackAlmost: "Close. Say: Turn left.",
    feedbackWrong: "Try: Turn left.",
    summary: "Turn + direction.",
  },
  "a1_review_order": {
    hint: ["Polite ordering."],
    explanation: "Use “I'd like …, please” to order politely.",
    feedbackAlmost: "Close. Use: I'd like a coffee, please.",
    feedbackWrong: "Try: I'd like a coffee, please.",
    summary: "I'd like …, please.",
  },
};
